### ISSUE TITLE
Admin Area

### ISSUE THREAD

**Issue by DavidNordicInternational** [mansisindhu/epic-games#44]
Hi! This a really cool project. Does this have any Admin Area?

**Comment by mansisindhu** [comment]
Hey David, glad you liked it. 
No, it doesn't have any admin. We had to build it within a week, so focused just on the user facing app.

**Comment by DavidNordicInternational** [comment]
Okey, if you need any help? I can contribute.

**Comment by mansisindhu** [comment]
I'm not going to maintain this project or anything, this is just a project submission. But if you want to work on it, that would be great. Please go ahead. 
Do let me know if you need any help.
